// AUTO-GENERATED by scripts/build-ambience.mjs — do not edit by hand.

export const AMBIENCE: { bed: number[]; rhythm: number[]; accents: number[] } = {
  bed: [
  ],
  rhythm: [
  ],
  accents: [
  ],
};
