#!/usr/bin/env node
/**
 * Generates the voice-companion clips with ElevenLabs and rewrites
 * src/data/voiceManifest.ts so the app bundles them.
 *
 *   npm run voice                 # default language: tr
 *   npm run voice -- --lang tr --force
 *   npm run voice -- --only tr_flow_01
 *
 * Settings come from the environment or from mobile/.env.local (git-ignored):
 *   ELEVENLABS_API_KEY=...        (required)
 *   ELEVENLABS_VOICE_ID=...       (required: voice to use)
 *   ELEVENLABS_MODEL=eleven_multilingual_v2   (or eleven_v3 for [whispers] tags)
 *
 * Existing mp3 files are skipped unless --force is given, so re-running only
 * fills in new or deleted lines.
 */
import { Buffer } from 'node:buffer';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

function loadEnvFile() {
  let f = path.join(root, '.env.local');
  // Windows Notepad often saves it as ".env.local.txt".
  if (!fs.existsSync(f) && fs.existsSync(f + '.txt')) {
    console.warn('Note: using .env.local.txt (rename it to .env.local when you can).');
    f += '.txt';
  }
  if (!fs.existsSync(f)) {
    console.warn(`No settings file found at ${path.join(root, '.env.local')}`);
    return;
  }
  for (const line of fs.readFileSync(f, 'utf8').split(/\r?\n/)) {
    const m = line.replace(/^\uFEFF/, '').match(/^\s*([A-Z0-9_]+)\s*=\s*(.*?)\s*$/);
    if (m && !process.env[m[1]]) process.env[m[1]] = m[2].replace(/^["']|["']$/g, '');
  }
}

function arg(name, fallback) {
  const i = process.argv.indexOf(`--${name}`);
  return i > -1 ? process.argv[i + 1] : fallback;
}

loadEnvFile();
const lang = arg('lang', 'tr');
const only = arg('only', null);
const force = process.argv.includes('--force');
const apiKey = process.env.ELEVENLABS_API_KEY;
const voiceId = process.env.ELEVENLABS_VOICE_ID;
const model = process.env.ELEVENLABS_MODEL || 'eleven_multilingual_v2';
const isV3 = model.startsWith('eleven_v3');

const linesFile = path.join(root, 'voice', `lines.${lang}.json`);
if (!fs.existsSync(linesFile)) {
  console.error(`No line file: ${linesFile}`);
  process.exit(1);
}
const lines = Object.values(JSON.parse(fs.readFileSync(linesFile, 'utf8')).groups).flat();
const outDir = path.join(root, 'assets', 'voice', lang);
fs.mkdirSync(outDir, { recursive: true });

// Soft, breathy, intimate delivery. v3 only accepts stability 0 / 0.5 / 1.
const voiceSettings = isV3
  ? { stability: 0.5, similarity_boost: 0.8 }
  : { stability: 0.32, similarity_boost: 0.8, style: 0.45, use_speaker_boost: true, speed: 0.9 };

async function synth(text) {
  const body = {
    text: isV3 ? `[whispers] ${text}` : text,
    model_id: model,
    voice_settings: voiceSettings,
    ...(isV3 ? { language_code: lang } : {}),
  };
  const res = await fetch(`https://api.elevenlabs.io/v1/text-to-speech/${voiceId}?output_format=mp3_44100_128`, {
    method: 'POST',
    headers: { 'xi-api-key': apiKey, 'Content-Type': 'application/json', Accept: 'audio/mpeg' },
    body: JSON.stringify(body),
  });
  if (!res.ok) {
    const detail = (await res.text()).slice(0, 300);
    const hint = res.status === 401 ? ' → API key is wrong or missing a permission (enable Text to Speech on the key).'
      : res.status === 404 ? ' → Voice ID not found. Add the voice to "My Voices" and copy its ID.'
        : res.status === 402 || /quota|credits/i.test(detail) ? ' → Not enough ElevenLabs credits / plan limit.'
          : res.status === 400 && /model/i.test(detail) ? ' → Model not available on your plan; try ELEVENLABS_MODEL=eleven_multilingual_v2.'
            : '';
    throw new Error(`HTTP ${res.status}: ${detail}${hint}`);
  }
  return Buffer.from(await res.arrayBuffer());
}

function writeManifest() {
  const base = path.join(root, 'assets', 'voice');
  const langs = fs.existsSync(base) ? fs.readdirSync(base).filter((d) => fs.statSync(path.join(base, d)).isDirectory()) : [];
  const out = ['// AUTO-GENERATED by scripts/generate-voice.mjs — do not edit by hand.', '', 'export const VOICE_CLIPS: Record<string, Record<string, number>> = {'];
  for (const l of langs.sort()) {
    const files = fs.readdirSync(path.join(base, l)).filter((f) => f.endsWith('.mp3')).sort();
    if (!files.length) continue;
    out.push(`  ${JSON.stringify(l)}: {`);
    for (const f of files) out.push(`    ${JSON.stringify(f.replace(/\.mp3$/, ''))}: require('../../assets/voice/${l}/${f}'),`);
    out.push('  },');
  }
  out.push('};', '');
  fs.writeFileSync(path.join(root, 'src', 'data', 'voiceManifest.ts'), out.join('\n'));
}

async function main() {
  if (!apiKey || !voiceId) {
    console.error('Set ELEVENLABS_API_KEY and ELEVENLABS_VOICE_ID (environment or mobile/.env.local).');
    process.exit(1);
  }
  console.log(`Model ${model}, voice ${voiceId}, language ${lang}, ${lines.length} lines`);
  let made = 0;
  let failed = 0;
  for (const l of lines) {
    if (only && l.id !== only) continue;
    const file = path.join(outDir, `${l.id}.mp3`);
    if (fs.existsSync(file) && !force) continue;
    try {
      fs.writeFileSync(file, await synth(l.text));
      made++;
      console.log(`✓ ${l.id}  ${l.text}`);
    } catch (e) {
      failed++;
      console.error(`✗ ${l.id}: ${e.message}`);
    }
  }
  // Remove clips whose line was deleted from the line file.
  if (!only) {
    const keep = new Set(lines.map((l) => `${l.id}.mp3`));
    for (const f of fs.readdirSync(outDir)) {
      if (f.endsWith('.mp3') && !keep.has(f)) {
        fs.unlinkSync(path.join(outDir, f));
        console.log(`– removed old clip ${f}`);
      }
    }
  }
  writeManifest();
  console.log(`\nDone: ${made} generated, ${failed} failed. Manifest updated.`);
  if (failed) process.exitCode = 1;
}

main();
